---
- name: snapper role
  tags:
    - snapper
  block:

  # check if installed
  - name: Check apt if snapper is already installed
    become: true
    ansible.builtin.apt:
      name: snapper
      state: present
    check_mode: true # outputs "changed": false || "changed": true
    ignore_errors: true
    register: _apt_snapper

  # assert
  - name: Check conditions for snapper
    ansible.builtin.assert:
      that:
      - _apt_snapper.changed == false # no change -> already installed

  # snapper add config
  - when: snapper.configs.add | length > 0
    name: Copy {{ snapper.configs.add }} to /etc/snapper/configs
    become: true
    loop: "{{ snapper.configs.add }}"
    ansible.builtin.copy:
      src: "configs/{{ item }}"
      dest: "/etc/snapper/configs/{{ item.split('/')[-1] }}" # fk/opt => opt
      owner: root
      group: root
      mode: u=rw,g=,o=

  # snapper rm config
  - when: snapper.configs.rm | length > 0
    name: Remove {{ snapper.configs.rm }} to /etc/snapper/configs
    become: true
    loop: "{{ snapper.configs.rm }}"
    ansible.builtin.file:
      path: "/etc/snapper/configs/{{ item.split('/')[-1] }}" # fk/opt => opt
      state: absent

  # systemd
  - ansible.builtin.import_tasks: systemd.yml
  
  # apt pre post mechanism
  - block:
      
    - when: snapper.apt.pre_post.state == "absent"
      name: Remove /etc/apt/apt.conf.d/80snapper
      become: true
      ansible.builtin.file:
        path: /etc/apt/apt.conf.d/80snapper
        state: absent